// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.28.1
// 	protoc        v3.21.11
// source: protobuf/advertisment.proto

package advertisment_grpc

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateAdvertismentInput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Name                string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Categories          []string `protobuf:"bytes,2,rep,name=categories,proto3" json:"categories,omitempty"`
	Description         string   `protobuf:"bytes,3,opt,name=description,proto3" json:"description,omitempty"`
	Price               *Price   `protobuf:"bytes,4,opt,name=price,proto3" json:"price,omitempty"`
	MainPhotoURL        string   `protobuf:"bytes,5,opt,name=mainPhotoURL,proto3" json:"mainPhotoURL,omitempty"`
	AdditionalPhotoURLs []string `protobuf:"bytes,6,rep,name=additionalPhotoURLs,proto3" json:"additionalPhotoURLs,omitempty"`
}

func (x *CreateAdvertismentInput) Reset() {
	*x = CreateAdvertismentInput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_advertisment_proto_msgTypes[0]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAdvertismentInput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdvertismentInput) ProtoMessage() {}

func (x *CreateAdvertismentInput) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_advertisment_proto_msgTypes[0]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdvertismentInput.ProtoReflect.Descriptor instead.
func (*CreateAdvertismentInput) Descriptor() ([]byte, []int) {
	return file_protobuf_advertisment_proto_rawDescGZIP(), []int{0}
}

func (x *CreateAdvertismentInput) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

func (x *CreateAdvertismentInput) GetCategories() []string {
	if x != nil {
		return x.Categories
	}
	return nil
}

func (x *CreateAdvertismentInput) GetDescription() string {
	if x != nil {
		return x.Description
	}
	return ""
}

func (x *CreateAdvertismentInput) GetPrice() *Price {
	if x != nil {
		return x.Price
	}
	return nil
}

func (x *CreateAdvertismentInput) GetMainPhotoURL() string {
	if x != nil {
		return x.MainPhotoURL
	}
	return ""
}

func (x *CreateAdvertismentInput) GetAdditionalPhotoURLs() []string {
	if x != nil {
		return x.AdditionalPhotoURLs
	}
	return nil
}

type CreateAdvertismentOutput struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Id string `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
}

func (x *CreateAdvertismentOutput) Reset() {
	*x = CreateAdvertismentOutput{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_advertisment_proto_msgTypes[1]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *CreateAdvertismentOutput) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateAdvertismentOutput) ProtoMessage() {}

func (x *CreateAdvertismentOutput) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_advertisment_proto_msgTypes[1]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateAdvertismentOutput.ProtoReflect.Descriptor instead.
func (*CreateAdvertismentOutput) Descriptor() ([]byte, []int) {
	return file_protobuf_advertisment_proto_rawDescGZIP(), []int{1}
}

func (x *CreateAdvertismentOutput) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

type Price struct {
	state         protoimpl.MessageState
	sizeCache     protoimpl.SizeCache
	unknownFields protoimpl.UnknownFields

	Value    float32 `protobuf:"fixed32,1,opt,name=value,proto3" json:"value,omitempty"`
	Currency string  `protobuf:"bytes,2,opt,name=currency,proto3" json:"currency,omitempty"`
}

func (x *Price) Reset() {
	*x = Price{}
	if protoimpl.UnsafeEnabled {
		mi := &file_protobuf_advertisment_proto_msgTypes[2]
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		ms.StoreMessageInfo(mi)
	}
}

func (x *Price) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Price) ProtoMessage() {}

func (x *Price) ProtoReflect() protoreflect.Message {
	mi := &file_protobuf_advertisment_proto_msgTypes[2]
	if protoimpl.UnsafeEnabled && x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Price.ProtoReflect.Descriptor instead.
func (*Price) Descriptor() ([]byte, []int) {
	return file_protobuf_advertisment_proto_rawDescGZIP(), []int{2}
}

func (x *Price) GetValue() float32 {
	if x != nil {
		return x.Value
	}
	return 0
}

func (x *Price) GetCurrency() string {
	if x != nil {
		return x.Currency
	}
	return ""
}

var File_protobuf_advertisment_proto protoreflect.FileDescriptor

var file_protobuf_advertisment_proto_rawDesc = []byte{
	0x0a, 0x1b, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x62, 0x75, 0x66, 0x2f, 0x61, 0x64, 0x76, 0x65, 0x72,
	0x74, 0x69, 0x73, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0c, 0x61,
	0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x6d, 0x65, 0x6e, 0x74, 0x22, 0xf0, 0x01, 0x0a, 0x17,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x6d, 0x65,
	0x6e, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x12, 0x12, 0x0a, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x18,
	0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x6e, 0x61, 0x6d, 0x65, 0x12, 0x1e, 0x0a, 0x0a, 0x63,
	0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x18, 0x02, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x0a, 0x63, 0x61, 0x74, 0x65, 0x67, 0x6f, 0x72, 0x69, 0x65, 0x73, 0x12, 0x20, 0x0a, 0x0b, 0x64,
	0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09,
	0x52, 0x0b, 0x64, 0x65, 0x73, 0x63, 0x72, 0x69, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x29, 0x0a,
	0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x18, 0x04, 0x20, 0x01, 0x28, 0x0b, 0x32, 0x13, 0x2e, 0x61,
	0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x50, 0x72, 0x69, 0x63,
	0x65, 0x52, 0x05, 0x70, 0x72, 0x69, 0x63, 0x65, 0x12, 0x22, 0x0a, 0x0c, 0x6d, 0x61, 0x69, 0x6e,
	0x50, 0x68, 0x6f, 0x74, 0x6f, 0x55, 0x52, 0x4c, 0x18, 0x05, 0x20, 0x01, 0x28, 0x09, 0x52, 0x0c,
	0x6d, 0x61, 0x69, 0x6e, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x55, 0x52, 0x4c, 0x12, 0x30, 0x0a, 0x13,
	0x61, 0x64, 0x64, 0x69, 0x74, 0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x55,
	0x52, 0x4c, 0x73, 0x18, 0x06, 0x20, 0x03, 0x28, 0x09, 0x52, 0x13, 0x61, 0x64, 0x64, 0x69, 0x74,
	0x69, 0x6f, 0x6e, 0x61, 0x6c, 0x50, 0x68, 0x6f, 0x74, 0x6f, 0x55, 0x52, 0x4c, 0x73, 0x22, 0x2a,
	0x0a, 0x18, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73,
	0x6d, 0x65, 0x6e, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75, 0x74, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64,
	0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x22, 0x39, 0x0a, 0x05, 0x50, 0x72,
	0x69, 0x63, 0x65, 0x12, 0x14, 0x0a, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x18, 0x01, 0x20, 0x01,
	0x28, 0x02, 0x52, 0x05, 0x76, 0x61, 0x6c, 0x75, 0x65, 0x12, 0x1a, 0x0a, 0x08, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x08, 0x63, 0x75, 0x72,
	0x72, 0x65, 0x6e, 0x63, 0x79, 0x32, 0x7a, 0x0a, 0x13, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69,
	0x73, 0x6d, 0x65, 0x6e, 0x74, 0x48, 0x61, 0x6e, 0x64, 0x6c, 0x65, 0x72, 0x12, 0x63, 0x0a, 0x12,
	0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x6d, 0x65,
	0x6e, 0x74, 0x12, 0x25, 0x2e, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x6d, 0x65, 0x6e,
	0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73,
	0x6d, 0x65, 0x6e, 0x74, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x1a, 0x26, 0x2e, 0x61, 0x64, 0x76, 0x65,
	0x72, 0x74, 0x69, 0x73, 0x6d, 0x65, 0x6e, 0x74, 0x2e, 0x43, 0x72, 0x65, 0x61, 0x74, 0x65, 0x41,
	0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x6d, 0x65, 0x6e, 0x74, 0x4f, 0x75, 0x74, 0x70, 0x75,
	0x74, 0x42, 0x15, 0x5a, 0x13, 0x2e, 0x3b, 0x61, 0x64, 0x76, 0x65, 0x72, 0x74, 0x69, 0x73, 0x6d,
	0x65, 0x6e, 0x74, 0x5f, 0x67, 0x72, 0x70, 0x63, 0x62, 0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
}

var (
	file_protobuf_advertisment_proto_rawDescOnce sync.Once
	file_protobuf_advertisment_proto_rawDescData = file_protobuf_advertisment_proto_rawDesc
)

func file_protobuf_advertisment_proto_rawDescGZIP() []byte {
	file_protobuf_advertisment_proto_rawDescOnce.Do(func() {
		file_protobuf_advertisment_proto_rawDescData = protoimpl.X.CompressGZIP(file_protobuf_advertisment_proto_rawDescData)
	})
	return file_protobuf_advertisment_proto_rawDescData
}

var file_protobuf_advertisment_proto_msgTypes = make([]protoimpl.MessageInfo, 3)
var file_protobuf_advertisment_proto_goTypes = []interface{}{
	(*CreateAdvertismentInput)(nil),  // 0: advertisment.CreateAdvertismentInput
	(*CreateAdvertismentOutput)(nil), // 1: advertisment.CreateAdvertismentOutput
	(*Price)(nil),                    // 2: advertisment.Price
}
var file_protobuf_advertisment_proto_depIdxs = []int32{
	2, // 0: advertisment.CreateAdvertismentInput.price:type_name -> advertisment.Price
	0, // 1: advertisment.AdvertismentHandler.CreateAdvertisment:input_type -> advertisment.CreateAdvertismentInput
	1, // 2: advertisment.AdvertismentHandler.CreateAdvertisment:output_type -> advertisment.CreateAdvertismentOutput
	2, // [2:3] is the sub-list for method output_type
	1, // [1:2] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_protobuf_advertisment_proto_init() }
func file_protobuf_advertisment_proto_init() {
	if File_protobuf_advertisment_proto != nil {
		return
	}
	if !protoimpl.UnsafeEnabled {
		file_protobuf_advertisment_proto_msgTypes[0].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAdvertismentInput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_advertisment_proto_msgTypes[1].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*CreateAdvertismentOutput); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
		file_protobuf_advertisment_proto_msgTypes[2].Exporter = func(v interface{}, i int) interface{} {
			switch v := v.(*Price); i {
			case 0:
				return &v.state
			case 1:
				return &v.sizeCache
			case 2:
				return &v.unknownFields
			default:
				return nil
			}
		}
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: file_protobuf_advertisment_proto_rawDesc,
			NumEnums:      0,
			NumMessages:   3,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_protobuf_advertisment_proto_goTypes,
		DependencyIndexes: file_protobuf_advertisment_proto_depIdxs,
		MessageInfos:      file_protobuf_advertisment_proto_msgTypes,
	}.Build()
	File_protobuf_advertisment_proto = out.File
	file_protobuf_advertisment_proto_rawDesc = nil
	file_protobuf_advertisment_proto_goTypes = nil
	file_protobuf_advertisment_proto_depIdxs = nil
}
