// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	usecase "github.com/bells307/adv-service/internal/usecase"
	mock "github.com/stretchr/testify/mock"
)

// CreateCategoryUseCase is an autogenerated mock type for the CreateCategoryUseCase type
type CreateCategoryUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *CreateCategoryUseCase) Execute(_a0 context.Context, _a1 usecase.CreateCategoryInput) (usecase.CreateCategoryOutput, error) {
	ret := _m.Called(_a0, _a1)

	var r0 usecase.CreateCategoryOutput
	if rf, ok := ret.Get(0).(func(context.Context, usecase.CreateCategoryInput) usecase.CreateCategoryOutput); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Get(0).(usecase.CreateCategoryOutput)
	}

	var r1 error
	if rf, ok := ret.Get(1).(func(context.Context, usecase.CreateCategoryInput) error); ok {
		r1 = rf(_a0, _a1)
	} else {
		r1 = ret.Error(1)
	}

	return r0, r1
}

type mockConstructorTestingTNewCreateCategoryUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewCreateCategoryUseCase creates a new instance of CreateCategoryUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewCreateCategoryUseCase(t mockConstructorTestingTNewCreateCategoryUseCase) *CreateCategoryUseCase {
	mock := &CreateCategoryUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
