// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	context "context"

	usecase "github.com/bells307/adv-service/internal/usecase"
	mock "github.com/stretchr/testify/mock"
)

// DeleteCategoryUseCase is an autogenerated mock type for the DeleteCategoryUseCase type
type DeleteCategoryUseCase struct {
	mock.Mock
}

// Execute provides a mock function with given fields: _a0, _a1
func (_m *DeleteCategoryUseCase) Execute(_a0 context.Context, _a1 usecase.DeleteCategoryInput) error {
	ret := _m.Called(_a0, _a1)

	var r0 error
	if rf, ok := ret.Get(0).(func(context.Context, usecase.DeleteCategoryInput) error); ok {
		r0 = rf(_a0, _a1)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}

type mockConstructorTestingTNewDeleteCategoryUseCase interface {
	mock.TestingT
	Cleanup(func())
}

// NewDeleteCategoryUseCase creates a new instance of DeleteCategoryUseCase. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewDeleteCategoryUseCase(t mockConstructorTestingTNewDeleteCategoryUseCase) *DeleteCategoryUseCase {
	mock := &DeleteCategoryUseCase{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
