// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/bells307/adv-service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	usecase "github.com/bells307/adv-service/internal/usecase"
)

// FindAdvertismentPresenter is an autogenerated mock type for the FindAdvertismentPresenter type
type FindAdvertismentPresenter struct {
	mock.Mock
}

// Output provides a mock function with given fields: _a0
func (_m *FindAdvertismentPresenter) Output(_a0 domain.Advertisment) usecase.FindAdvertismentOutput {
	ret := _m.Called(_a0)

	var r0 usecase.FindAdvertismentOutput
	if rf, ok := ret.Get(0).(func(domain.Advertisment) usecase.FindAdvertismentOutput); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(usecase.FindAdvertismentOutput)
	}

	return r0
}

type mockConstructorTestingTNewFindAdvertismentPresenter interface {
	mock.TestingT
	Cleanup(func())
}

// NewFindAdvertismentPresenter creates a new instance of FindAdvertismentPresenter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFindAdvertismentPresenter(t mockConstructorTestingTNewFindAdvertismentPresenter) *FindAdvertismentPresenter {
	mock := &FindAdvertismentPresenter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
