// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/bells307/adv-service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	usecase "github.com/bells307/adv-service/internal/usecase"
)

// FindAllAdvertismentSummaryPresenter is an autogenerated mock type for the FindAllAdvertismentSummaryPresenter type
type FindAllAdvertismentSummaryPresenter struct {
	mock.Mock
}

// Output provides a mock function with given fields: _a0
func (_m *FindAllAdvertismentSummaryPresenter) Output(_a0 []domain.AdvertismentSummary) usecase.FindAllAdvertismentSummaryOutput {
	ret := _m.Called(_a0)

	var r0 usecase.FindAllAdvertismentSummaryOutput
	if rf, ok := ret.Get(0).(func([]domain.AdvertismentSummary) usecase.FindAllAdvertismentSummaryOutput); ok {
		r0 = rf(_a0)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(usecase.FindAllAdvertismentSummaryOutput)
		}
	}

	return r0
}

type mockConstructorTestingTNewFindAllAdvertismentSummaryPresenter interface {
	mock.TestingT
	Cleanup(func())
}

// NewFindAllAdvertismentSummaryPresenter creates a new instance of FindAllAdvertismentSummaryPresenter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFindAllAdvertismentSummaryPresenter(t mockConstructorTestingTNewFindAllAdvertismentSummaryPresenter) *FindAllAdvertismentSummaryPresenter {
	mock := &FindAllAdvertismentSummaryPresenter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
