// Code generated by mockery v2.15.0. DO NOT EDIT.

package mocks

import (
	domain "github.com/bells307/adv-service/internal/domain"
	mock "github.com/stretchr/testify/mock"

	usecase "github.com/bells307/adv-service/internal/usecase"
)

// FindCategoryPresenter is an autogenerated mock type for the FindCategoryPresenter type
type FindCategoryPresenter struct {
	mock.Mock
}

// Output provides a mock function with given fields: _a0
func (_m *FindCategoryPresenter) Output(_a0 domain.Category) usecase.FindCategoryOutput {
	ret := _m.Called(_a0)

	var r0 usecase.FindCategoryOutput
	if rf, ok := ret.Get(0).(func(domain.Category) usecase.FindCategoryOutput); ok {
		r0 = rf(_a0)
	} else {
		r0 = ret.Get(0).(usecase.FindCategoryOutput)
	}

	return r0
}

type mockConstructorTestingTNewFindCategoryPresenter interface {
	mock.TestingT
	Cleanup(func())
}

// NewFindCategoryPresenter creates a new instance of FindCategoryPresenter. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
func NewFindCategoryPresenter(t mockConstructorTestingTNewFindCategoryPresenter) *FindCategoryPresenter {
	mock := &FindCategoryPresenter{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}
